package com.ipc1.modos;

import com.ipc1.constructores.animales;

public class tiers {
    // tier 1
    animales arreglotier1[] = {
            new animales("Hormiga", 2, 1, "Insecto/Terrestre"),
            new animales("Pescado", 2, 3, "Acuatico"),
            new animales("Mosquito", 2, 2, "Volador"),
            new animales("Grillo", 1, 2, "Insecto"),
            new animales("Castor", 2, 2, "Terrestre/Acuatico"),
            new animales("Caballo", 2, 1, "Mamifero/Domestico"),
            new animales("Nutria", 1, 2, "Mamifero"),
            new animales("Escarabajo", 2, 3, "Insecto"), };
    // tier2+tier1
    animales arreglotier2[] = {
            new animales("Hormiga", 2, 1, "Insecto/Terrestre"),
            new animales("Pescado", 2, 3, "Acuatico"),
            new animales("Mosquito", 2, 2, "Volador"),
            new animales("Grillo", 1, 2, "Insecto"),
            new animales("Castor", 2, 2, "Terrestre/Acuatico"),
            new animales("Caballo", 2, 1, "Mamifero/Domestico"),
            new animales("Nutria", 1, 2, "Mamifero"),
            new animales("Escarabajo", 2, 3, "Insecto"),
            new animales("Sapo", 3, 3, "Terrestre/Acuatico"),
            new animales("Dodo", 2, 3, "Volador"),
            new animales("Elefante", 3, 5, "Mamifero/Terrestre"),
            new animales("Puerco Espin", 3, 2, "Solitario/Terrestre"),
            new animales("Pavorreal", 2, 5, "Domestico/Volador"),
            new animales("Rata", 4, 5, "Terrestre/Solitario"),
            new animales("Zorro", 5, 2, "Solitario/Terrestre"),
            new animales("Arana", 2, 2, "Insecto") };
    // Tier 3+
    animales arreglotier3[] = {
            new animales("Hormiga", 2, 1, "Insecto/Terrestre"),
            new animales("Pescado", 2, 3, "Acuatico"),
            new animales("Mosquito", 2, 2, "Volador"),
            new animales("Grillo", 1, 2, "Insecto"),
            new animales("Castor", 2, 2, "Terrestre/Acuatico"),
            new animales("Caballo", 2, 1, "Mamifero/Domestico"),
            new animales("Nutria", 1, 2, "Mamifero"),
            new animales("Escarabajo", 2, 3, "Insecto"),
            new animales("Sapo", 3, 3, "Terrestre/Acuatico"),
            new animales("Dodo", 2, 3, "Volador"),
            new animales("Elefante", 3, 5, "Mamifero/Terrestre"),
            new animales("Puerco Espin", 3, 2, "Solitario/Terrestre"),
            new animales("Pavorreal", 2, 5, "Domestico/Volador"),
            new animales("Rata", 4, 5, "Terrestre/Solitario"),
            new animales("Zorro", 5, 2, "Solitario/Terrestre"),
            new animales("Arana", 2, 2, "Insecto"),
            new animales("Camello", 2, 5, "Mamifero/Desertico"),
            new animales("Mapache", 5, 4, "Solitario"),
            new animales("Jirafa", 2, 5, "Mamifero/Terrestre"),
            new animales("Tortuga", 1, 2, "reptil"),
            new animales("Caracol", 2, 2, "Insecto/Solitario"),
            new animales("Obeja(Cabra)", 2, 2, "Domestisco/Terrestre"),
            new animales("Conejo", 3, 2, "mamifero"),
            new animales("Lobo", 3, 4, "Solitario/Terrestre"),
            new animales("Buey", 1, 4, "Mamifero"),
            new animales("Canguro", 1, 2, "Mamifero/Terrestre"),
            new animales("Buho", 5, 3, "Volador/Solitario") };
    // Tier 4+
    animales arreglotier4[] = {
            new animales("Hormiga", 2, 1, "Insecto/Terrestre"),
            new animales("Pescado", 2, 3, "Acuatico"),
            new animales("Mosquito", 2, 2, "Volador"),
            new animales("Grillo", 1, 2, "Insecto"),
            new animales("Castor", 2, 2, "Terrestre/Acuatico"),
            new animales("Caballo", 2, 1, "Mamifero/Domestico"),
            new animales("Nutria", 1, 2, "Mamifero"),
            new animales("Escarabajo", 2, 3, "Insecto"),
            new animales("Sapo", 3, 3, "Terrestre/Acuatico"),
            new animales("Dodo", 2, 3, "Volador"),
            new animales("Elefante", 3, 5, "Mamifero/Terrestre"),
            new animales("Puerco Espin", 3, 2, "Solitario/Terrestre"),
            new animales("Pavorreal", 2, 5, "Domestico/Volador"),
            new animales("Rata", 4, 5, "Terrestre/Solitario"),
            new animales("Zorro", 5, 2, "Solitario/Terrestre"),
            new animales("Arana", 2, 2, "Insecto"),
            new animales("Camello", 2, 5, "Mamifero/Desertico"),
            new animales("Mapache", 5, 4, "Solitario"),
            new animales("Jirafa", 2, 5, "Mamifero/Terrestre"),
            new animales("Tortuga", 1, 2, "reptil"),
            new animales("Caracol", 2, 2, "Insecto/Solitario"),
            new animales("Obeja(Cabra)", 2, 2, "Domestisco/Terrestre"),
            new animales("Conejo", 3, 2, "mamifero"),
            new animales("Lobo", 3, 4, "Solitario/Terrestre"),
            new animales("Buey", 1, 4, "Mamifero"),
            new animales("Canguro", 1, 2, "Mamifero/Terrestre"),
            new animales("Buho", 5, 3, "Volador/Solitario"),
            new animales("Venado", 1, 1, "Mamifero"),
            new animales("Loro", 5, 3, "Volador"),
            new animales("Hipopotamo", 4, 7, "Acuatico/Terrestre"),
            new animales("Delfin", 4, 6, "Acautico"),
            new animales("Puma", 3, 7, "Mamifero/Terrestre"),
            new animales("Ballena", 3, 8, "Acuatico"),
            new animales("Ardilla", 2, 5, "Domestico"),
            new animales("Yama", 3, 6, "Terrestre") };
    // Tier 5+
    animales arreglotier5[] = {
            new animales("Hormiga", 2, 1, "Insecto/Terrestre"),
            new animales("Pescado", 2, 3, "Acuatico"),
            new animales("Mosquito", 2, 2, "Volador"),
            new animales("Grillo", 1, 2, "Insecto"),
            new animales("Castor", 2, 2, "Terrestre/Acuatico"),
            new animales("Caballo", 2, 1, "Mamifero/Domestico"),
            new animales("Nutria", 1, 2, "Mamifero"),
            new animales("Escarabajo", 2, 3, "Insecto"),
            new animales("Sapo", 3, 3, "Terrestre/Acuatico"),
            new animales("Dodo", 2, 3, "Volador"),
            new animales("Elefante", 3, 5, "Mamifero/Terrestre"),
            new animales("Puerco Espin", 3, 2, "Solitario/Terrestre"),
            new animales("Pavorreal", 2, 5, "Domestico/Volador"),
            new animales("Rata", 4, 5, "Terrestre/Solitario"),
            new animales("Zorro", 5, 2, "Solitario/Terrestre"),
            new animales("Arana", 2, 2, "Insecto"),
            new animales("Camello", 2, 5, "Mamifero/Desertico"),
            new animales("Mapache", 5, 4, "Solitario"),
            new animales("Jirafa", 2, 5, "Mamifero/Terrestre"),
            new animales("Tortuga", 1, 2, "reptil"),
            new animales("Caracol", 2, 2, "Insecto/Solitario"),
            new animales("Obeja(Cabra)", 2, 2, "Domestisco/Terrestre"),
            new animales("Conejo", 3, 2, "mamifero"),
            new animales("Lobo", 3, 4, "Solitario/Terrestre"),
            new animales("Buey", 1, 4, "Mamifero"),
            new animales("Canguro", 1, 2, "Mamifero/Terrestre"),
            new animales("Buho", 5, 3, "Volador/Solitario"),
            new animales("Venado", 1, 1, "Mamifero"),
            new animales("Loro", 5, 3, "Volador"),
            new animales("Hipopotamo", 4, 7, "Acuatico/Terrestre"),
            new animales("Delfin", 4, 6, "Acautico"),
            new animales("Puma", 3, 7, "Mamifero/Terrestre"),
            new animales("Ballena", 3, 8, "Acuatico"),
            new animales("Ardilla", 2, 5, "Domestico"),
            new animales("Yama", 3, 6, "Terrestre"),
            new animales("Foca", 3, 8, "Acuatico/Mamifero"),
            new animales("Jaguar", 7, 4, "Mamifero/Terrestre"),
            new animales("Escorpion", 1, 1, "Desertico/Solitario"),
            new animales("Rinoceronte", 5, 8, "Desertido/Terrestre"),
            new animales("Mono", 1, 2, "Mamifero"),
            new animales("Cocodrilo", 8, 4, "Reptil/Solitario"),
            new animales("Vaca", 4, 6, "Mamifero/Terrestre"),
            new animales("Chompipe", 3, 4, "Terrestre/Volador") };
    // Tier 6+
    animales arreglotier6[] = {
            new animales("Hormiga", 2, 1, "Insecto/Terrestre"),
            new animales("Pescado", 2, 3, "Acuatico"),
            new animales("Mosquito", 2, 2, "Volador"),
            new animales("Grillo", 1, 2, "Insecto"),
            new animales("Castor", 2, 2, "Terrestre/Acuatico"),
            new animales("Caballo", 2, 1, "Mamifero/Domestico"),
            new animales("Nutria", 1, 2, "Mamifero"),
            new animales("Escarabajo", 2, 3, "Insecto"),
            new animales("Sapo", 3, 3, "Terrestre/Acuatico"),
            new animales("Dodo", 2, 3, "Volador"),
            new animales("Elefante", 3, 5, "Mamifero/Terrestre"),
            new animales("Puerco Espin", 3, 2, "Solitario/Terrestre"),
            new animales("Pavorreal", 2, 5, "Domestico/Volador"),
            new animales("Rata", 4, 5, "Terrestre/Solitario"),
            new animales("Zorro", 5, 2, "Solitario/Terrestre"),
            new animales("Arana", 2, 2, "Insecto"),
            new animales("Camello", 2, 5, "Mamifero/Desertico"),
            new animales("Mapache", 5, 4, "Solitario"),
            new animales("Jirafa", 2, 5, "Mamifero/Terrestre"),
            new animales("Tortuga", 1, 2, "reptil"),
            new animales("Caracol", 2, 2, "Insecto/Solitario"),
            new animales("Obeja(Cabra)", 2, 2, "Domestisco/Terrestre"),
            new animales("Conejo", 3, 2, "mamifero"),
            new animales("Lobo", 3, 4, "Solitario/Terrestre"),
            new animales("Buey", 1, 4, "Mamifero"),
            new animales("Canguro", 1, 2, "Mamifero/Terrestre"),
            new animales("Buho", 5, 3, "Volador/Solitario"),
            new animales("Venado", 1, 1, "Mamifero"),
            new animales("Loro", 5, 3, "Volador"),
            new animales("Hipopotamo", 4, 7, "Acuatico/Terrestre"),
            new animales("Delfin", 4, 6, "Acautico"),
            new animales("Puma", 3, 7, "Mamifero/Terrestre"),
            new animales("Ballena", 3, 8, "Acuatico"),
            new animales("Ardilla", 2, 5, "Domestico"),
            new animales("Yama", 3, 6, "Terrestre"),
            new animales("Foca", 3, 8, "Acuatico/Mamifero"),
            new animales("Jaguar", 7, 4, "Mamifero/Terrestre"),
            new animales("Escorpion", 1, 1, "Desertico/Solitario"),
            new animales("Rinoceronte", 5, 8, "Desertido/Terrestre"),
            new animales("Mono", 1, 2, "Mamifero"),
            new animales("Cocodrilo", 8, 4, "Reptil/Solitario"),
            new animales("Vaca", 4, 6, "Mamifero/Terrestre"),
            new animales("Chompipe", 3, 4, "Terrestre/Volador"),
            new animales("Panda", 5, 5, "Mamifero/Solitario"),
            new animales("Gato", 4, 5, "Mamifero/Domestico"),
            new animales("Tigre", 4, 3, "Terrestre/Mamifero"),
            new animales("Serpiente", 6, 6, "Reptil/Terrestre/Desertico"),
            new animales("Mamut", 3, 10, "Mamifero/Terrestre/Solitario"),
            new animales("Leopardo", 10, 4, "Mamifero/Terrestre"),
            new animales("Gorila", 6, 9, "Mamifero/Terrestre"),
            new animales("Pulpo", 8, 8, "Acuatico/Solitario"),
            new animales("Mosca", 5, 5, "Volador/Insecto") };
    // Tier 7+
    animales arreglotier7[] = {
            new animales("Hormiga", 2, 1, "Insecto/Terrestre"),
            new animales("Pescado", 2, 3, "Acuatico"),
            new animales("Mosquito", 2, 2, "Volador"),
            new animales("Grillo", 1, 2, "Insecto"),
            new animales("Castor", 2, 2, "Terrestre/Acuatico"),
            new animales("Caballo", 2, 1, "Mamifero/Domestico"),
            new animales("Nutria", 1, 2, "Mamifero"),
            new animales("Escarabajo", 2, 3, "Insecto"),
            new animales("Sapo", 3, 3, "Terrestre/Acuatico"),
            new animales("Dodo", 2, 3, "Volador"),
            new animales("Elefante", 3, 5, "Mamifero/Terrestre"),
            new animales("Puerco Espin", 3, 2, "Solitario/Terrestre"),
            new animales("Pavorreal", 2, 5, "Domestico/Volador"),
            new animales("Rata", 4, 5, "Terrestre/Solitario"),
            new animales("Zorro", 5, 2, "Solitario/Terrestre"),
            new animales("Arana", 2, 2, "Insecto"),
            new animales("Camello", 2, 5, "Mamifero/Desertico"),
            new animales("Mapache", 5, 4, "Solitario"),
            new animales("Jirafa", 2, 5, "Mamifero/Terrestre"),
            new animales("Tortuga", 1, 2, "reptil"),
            new animales("Caracol", 2, 2, "Insecto/Solitario"),
            new animales("Obeja(Cabra)", 2, 2, "Domestisco/Terrestre"),
            new animales("Conejo", 3, 2, "mamifero"),
            new animales("Lobo", 3, 4, "Solitario/Terrestre"),
            new animales("Buey", 1, 4, "Mamifero"),
            new animales("Canguro", 1, 2, "Mamifero/Terrestre"),
            new animales("Buho", 5, 3, "Volador/Solitario"),
            new animales("Venado", 1, 1, "Mamifero"),
            new animales("Loro", 5, 3, "Volador"),
            new animales("Hipopotamo", 4, 7, "Acuatico/Terrestre"),
            new animales("Delfin", 4, 6, "Acautico"),
            new animales("Puma", 3, 7, "Mamifero/Terrestre"),
            new animales("Ballena", 3, 8, "Acuatico"),
            new animales("Ardilla", 2, 5, "Domestico"),
            new animales("Yama", 3, 6, "Terrestre"),
            new animales("Foca", 3, 8, "Acuatico/Mamifero"),
            new animales("Jaguar", 7, 4, "Mamifero/Terrestre"),
            new animales("Escorpion", 1, 1, "Desertico/Solitario"),
            new animales("Rinoceronte", 5, 8, "Desertido/Terrestre"),
            new animales("Mono", 1, 2, "Mamifero"),
            new animales("Cocodrilo", 8, 4, "Reptil/Solitario"),
            new animales("Vaca", 4, 6, "Mamifero/Terrestre"),
            new animales("Chompipe", 3, 4, "Terrestre/Volador"),
            new animales("Panda", 5, 5, "Mamifero/Solitario"),
            new animales("Gato", 4, 5, "Mamifero/Domestico"),
            new animales("Tigre", 4, 3, "Terrestre/Mamifero"),
            new animales("Serpiente", 6, 6, "Reptil/Terrestre/Desertico"),
            new animales("Mamut", 3, 10, "Mamifero/Terrestre/Solitario"),
            new animales("Leopardo", 10, 4, "Mamifero/Terrestre"),
            new animales("Gorila", 6, 9, "Mamifero/Terrestre"),
            new animales("Pulpo", 8, 8, "Acuatico/Solitario"),
            new animales("Mosca", 5, 5, "Volador/Insecto"),
            new animales("Quetzal", 10, 10, "Volador/Solitario"),
            new animales("Camaleon", 8, 8, "Reptil/Solitario") };

}
